apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: secrets
  labels:
    app: primeiro-pod
spec:
  containers:
    - name: container-pod
      image: nginx:latest
      ports:
       - containerPort: 80
      envFrom:
      - secretRef:
          name: mysecret