apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-prod
  labels:
    app: webapp
spec:
  replicas: 9
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: gcr.io/lab-gke-355014/webapp:v1
        ports:
        - containerPort: 5000